FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o anbu .

FROM scratch

COPY --from=builder /app/anbu /anbu
EXPOSE 8080
ENTRYPOINT ["/anbu", "fs-sync", "server", "-d", "/data"]
